### ISSUE TITLE
Complex bindings problem

### ISSUE THREAD

**Issue by phajy** [fjebaker/SpectralFitting.jl#124]
I _think_ that, e.g.,

```julia
push!(prob.bindings, [1 => 1, 4 => 1, 5 => 1])
push!(prob.bindings, [2 => 1, 6 => 1, 7 => 1])
```

has the same effect as

```julia
push!(prob.bindings, [1 => 1, 2 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1])
```

I was intending for parameter 1 (e.g., normalisation) to be bound together for data sets 1, 4, and 5 with a single value, and to be bound together for data sets 2, 6, and 7 with a separate (different) value.

A workaround is just to use two different models which I will use instead.

Thought I'd flag this now as a placeholder in case anyone else runs into a similar issue.

**Comment by fjebaker** [comment]
Let's use this thread to collect binding use cases that need to be addressed.
- Bind different symbols together (`bind!(prob, :a_1, :b_1)` should bind all a and b for all data-model pairs).
- Bind only specific data-model pairs (`bind!(prob, 2 => :a_1, 4 => :a_1)` should bind the a parameter in the 2nd and 4th data-model pair).

**Comment by fjebaker** [comment]
Also need to be able to bind some parameter `:a` in model A to parameter `:b` in model B.
