### ISSUE TITLE
Subtract backgrounds

### ISSUE THREAD

**Issue by fjebaker** [fjebaker/SpectralFitting.jl#21]
With #20, there should be a further overhaul to let `SpectralDataset` hold onto most parts of OGIP, and flatten out some of the common meta fields (quality, grouping, etc.), and also hold onto the background spectrum, so this may be more easily subtracted.

**Comment by phajy** [comment]
Can you update `spectral-datasets.jl` and `xmm-newton-mission.jl` to include the background file. When I load an *XMM-Newton* data set it loads the spectrum, RMF, and ARF as specified in the spectrum header, but not the background file.

**Comment by fjebaker** [comment]
@phajy Have been working on this today. I am in the progress of a larger parser rewrite since #45, so this should hopefully not take too long.

**Comment by fjebaker** [comment]
After
- #48 

then background subtracting can be implemented. I think the easiest way to do it is when we assemble the target vector for fitting.

Will add a `background_subtracted_target_vector` method for this. This can then be extended without too much difficulty to support other background models, depending on the type of the background in `SpectralDataset`. This is currently fixed to `Union{Missing,Spectrum}` but it could be extended for some analytic background type, in which case only `background_subtracted_target_vector` would need to updated for the fitting to still be able to work okay.
