### ISSUE TITLE
Background subtraction for simple datasets

### ISSUE THREAD

**Issue by phajy** [fjebaker/SpectralFitting.jl#52]
Need to add a function for background subtracting simple datasets that, at the moment, does nothing (or requires `subtract_background = false` to be passed). This would need to implement `background_subtracted_target_variance` and `background_subtracted_target_vector` in `simple-dataset.jl` but for type `::SimpleDataset` rather than `::SpectralDataset`.

**Comment by fjebaker** [comment]
The notion of automatic background subtraction is now gone as of #61 so this can be closed.

If a simple dataset has a background, the user should manually subtract it (perhaps using one of our many utility methods) before fitting, or else add a fiting transformation that adds the background before the fit statistic is calculated during fit.
