### ISSUE TITLE
New XSPEC model

### ISSUE THREAD

**Issue by phajy** [fjebaker/SpectralFitting.jl#59]
It would be good if SepctralFitting could use the [WARMABS XSPEC model](https://heasarc.gsfc.nasa.gov/xstar/docs/html/node102.html). I have used this in the distant past, but am now downloading and testing it in XSPEC. Unsurprisingly it is very large, around ~2+ GB (?), because it includes lots of tables. I don't know how easy it is to compile outside of XSPEC but it might not be too bad because it was originally designed to run as a standalone code.

**Comment by fjebaker** [comment]
Done. Only `warmabs` is currently wrapped, but it's trivial to add the others if they are needed. Model data is stored seperately on the Bristol servers, so will need to download individually -- but an error string will pop up with instructions the first time you try to invoke the model with instructions on how to do that :)

**Comment by fjebaker** [comment]
See 
- https://github.com/astro-group-bristol/SpectralFittingExtras.jl/tree/main/Warmabs
