### ISSUE TITLE
Failed to precompile SpectralFitting

### ISSUE THREAD

**Issue by phajy** [fjebaker/SpectralFitting.jl#64]
SpectralFitting is failing to precompile with the following error message

```julia
ERROR: LoadError: UndefVarError: `FittableMultiModel` not defined
```

**Comment by phajy** [comment]
Now the above problem has been fixed we've run into an array indexing problem. This can be reproduced by running, e.g., [LoadData.jl](https://github.com/phajy/TestingGR/blob/main/src/LoadData.jl) which fails on [this line](https://github.com/phajy/TestingGR/blob/10285d4ed794b2e578858a5724a1226648dd8eb0/src/LoadData.jl#L38C4-L38C4), producing the following error message

```julia
ERROR: BoundsError: attempt to access 231×2067 SparseArrays.SparseMatrixCSC{Float64, Int64} with 90405 stored entries at index [[20, 31, 38, 45, 52, 59, 66, 73, 80, 87  …  2695, 2712, 2733, 2772, 2808, 2835, 2864, 2895, 2929, 2961], 1:2067]
```

**Comment by phajy** [comment]
I think the issue is with, e.g.,

https://github.com/fjebaker/SpectralFitting.jl/blob/5aa5cb9cc6961fc6b0c9be970d3332675c740c25/src/datasets/response.jl#L108-L114

specifically with trying to evaluate `response.matrix[channels, :]` where `channels` is a list of channels rather than the index in the response matrix. The size of the first dimension of `matrix` matches the size of the number of channels in the spectrum (`spectrum.channels`).

I was trying to modify the noticed channels in the data set to be in range, because some of those channels seemed to be $> 2067$ but then discovered my logic is wrong! Dropping channels above 2067 didn't fix the issue.

Does the response matrix get modified in any way? I was surprised that the number of data channels matched the number of response channels. Of course when it comes down to the matrix multiplication there must be a size match, but I'm not sure when this happens.

Is there a workaround I could employ for the time being?

Thanks!

**Comment by fjebaker** [comment]
Hi @phajy ! I'm working on a fix for this. Will try and finish it tonight so that it wont bottleneck you any further! Sorry about the delay.

**Comment by fjebaker** [comment]
In master branch now. Won't hit the registry until #62 , so you'll have to pull to update :)

**Comment by fjebaker** [comment]
Note: there's a few things that don't quite make sense in the walkthrough I sent you, which imply other issues in the library too; e.g., dropping channels and regrouping the response matrix works seemingly okay for the XMM data I test on, but leads to unusual results in the EXOSAT data in the walkthrough. I roughly know what's going wrong, and will patch it when I get the chance.
