### ISSUE TITLE
The function `prettyfloat` doesn't work if its argument `f` can't be converted to Int64

### ISSUE THREAD

**Issue by phajy** [fjebaker/SpectralFitting.jl#86]
`trunc` doesn't work if `f` is too large, giving an error such as `ERROR: InexactError: trunc(Int64, 6.579332246575656e24)`

https://github.com/fjebaker/SpectralFitting.jl/blob/45683112cf18fd8fcdbd47c79071f5d8fc84405b/src/print-utilities.jl#L7

I guess we could either use a `try` or just format the number to 5 significant figures if it is larger than some threshold?

**Comment by fjebaker** [comment]
There are better ways we can do pretty float printing. I'd forgotten about that function, that was only ever supposed to be a quick hack! Thanks for the report, will patch when I get the time!

**Comment by fjebaker** [comment]
Closed in #87
